### ISSUE TITLE
Introducing DropErrorPublisher type

### ISSUE THREAD

**Issue by ddddxxx** [luoxiu/CombineX.Cocoa#2]
It could be useful converting `Publisher<T, Error>` to `Publisher<T, Never>`.

```swift
extension Publisher {
    func dropError() -> Publishers.DropError<Output, Never> {
        // it works just like `return map(Optional.init).replaceError(with: nil).compactMap { $0 }`
    }
}
```

If the upstream publisher fails with an error, this publisher discards the error, then finishes normally.

**Comment by luoxiu** [comment]
That makes sense. Maybe it should look like this:

```swift
self.upstream
    .catch { _ in
        Empty()
    }
    .receive(subscriber: subscriber)
```

Also, `drop`  in swift usually means `discard first ***`, like `list.dropFirst`, `list.dropWhile`, maybe, `discardError` is a better name?

**Comment by luoxiu** [comment]
可以加下微信吗？😬

**Comment by luoxiu** [comment]
Moved to [CXExtensions](https://github.com/cx-org/CXExtensions)
