### ISSUE TITLE
Introducing DelayedAutoCancellable type

### ISSUE THREAD

**Issue by ddddxxx** [luoxiu/CombineX.Cocoa#3]
```swift
extension Cancellable {
    public func cancel<S: Scheduler>(after interval: S.SchedulerTimeType.Stride, scheduler: S, options: S.SchedulerOptions? = nil) -> DelayedAutoCancellable {
        // Automatically get cancelled after specified time interval.
    }
}
```

**Comment by luoxiu** [comment]
Looks great!

**Comment by luoxiu** [comment]
嗨，@ddddxxx ，感谢你对 CombineX 的关注与参与！

作为目前的唯二贡献者(🤣)，我想和你讨论一些 CombineX 的问题。
我最近有在想把所有 CombineX.Repos 移动到一个单独的 organization 里，这不只为了方便管理，想让 CombineX 成为一个更加**开放**的平台是另一个更大的原因。
但身患选择强迫症的我在选择名字上遇到了一些麻烦，CombineX 无疑是最好的，但它已经被占用了，我脑海中还有一些其它备选：

- combinexs
- CombineXSwift
- CombineX-Swift
- CombineX-Org

你觉得呢？

**Comment by ddddxxx** [comment]
昨天给你发了邮件但是似乎你没有看😅。可以加我 Telegram: https://t.me/ddddxxxx

**Comment by luoxiu** [comment]
加过了，luoxiustm 设置的邮件转发失效了……刚才又验证了手机号才重新开启

**Comment by luoxiu** [comment]
Moved to [CXExtensions](https://github.com/cx-org/CXExtensions)
